# Generated by Django 2.2.9 on 2019-12-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('num_siblings', models.IntegerField(default=0)),
                ('env_exposures', models.CharField(max_length=200)),
                ('genetic_mutations', models.CharField(max_length=200)),
                ('review_status', models.IntegerField(default=0)),
            ],
        ),
    ]
